version: "3"
services:
  phoenix:
    build: .
    user: "${UID}:${GID}"
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
#    platform: linux/arm/v8
    image: "postgres:14.1-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
