version: "3"
services:
  phoenix:
    build: .
    user: "${UID}:${GID}"
    volumes:
      - ./src:/app
    ports:
      - "4000:4000"
    command: sleep infinity
    depends_on:
      - db
  db:
    image: "postgres:14.2-alpine"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
